<?php

/**
 * @file
 * This module implements SBSYS ESDH backend for use in os2web
 */

include_once('os2web_sbsys_esdh.features.inc');

define('MM_IMPORT_DIR', 'public://sbsys');
define('MM_DEFAULT_APPROVED', '62,59,64,53,54,56,57,63,58,51,55,61,68,69,42');

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Register as provider of esdh plugins
 */
function os2web_sbsys_esdh_ctools_plugin_directory($module, $plugin) {
  if ($module == 'os2web_esdh_provider') {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add configuration to the settings form.
 */
function os2web_sbsys_esdh_form_os2web_settings_settings_form_alter(&$form, &$form_state) {
  // MM configuration.
  $form['meetings'] = array(
    '#type' => 'fieldset',
    '#title' => 'Referat import',
    '#description' => 'Indstillinger der vedrører importen af SBSYS referater og dagsordener.',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['meetings']['os2web_sbsys_esdh_mm_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Sti til sbsys publish folder.',
    '#description' => 'Dette er stien hvor ESDH publisere .XML filer til.',
    '#default_value' => variable_get('os2web_sbsys_esdh_mm_path', MM_IMPORT_DIR),
  );
  $form['meetings']['os2web_sbsys_esdh_approved_committees'] = array(
    '#type' => 'textfield',
    '#title' => 'Godkendte Udvalg',
    '#maxlength' => 200,
    '#description' => 'Komma sepereret liste over udvalgs-id der er godkendt til publisering.',
    '#default_value' => variable_get('os2web_sbsys_esdh_approved_committees', MM_DEFAULT_APPROVED),
  );
}

/**
 * Implements hook_os2web_help().
 */
function os2web_sbsys_esdh_os2web_help($sections) {

  // Content types.
  $sections['configuration'] = t('<p><a href="@url" target="_blank">See the advanced documentation for sbsys</a></p>', array('@url' => url('admin/help/os2web_sbsys_esdh')));
  return $sections;
}

/**
 * Implements hook_help().
 */
function os2web_sbsys_esdh_help($path, $arg) {
  switch ($path) {
    case 'admin/help#os2web_sbsys_esdh':
      // TODO.
      return t('Missing documentation.');
  }
}
